### ISSUE TITLE
Jetson xavier

### ISSUE THREAD

**Issue by firatbozkaya** [krishnasandeep09/UKF#1]
hi krishna, when i run your code on pc it works fine. But when I run it on jetson xavier, in a short time x and y values ​​start to return Nan. What is your suggestion on this subject? Thanks.

**Comment by krishnasandeep09** [comment]
Hi Firat, 
I don't think the hardware should affect the code. Can you give more details on the setup you had for PC & Jetson Xavier (OS, ROS version, how you are fetching IMU & GNSS data etc)?

**Comment by firatbozkaya** [comment]
Hi Krishna, my problem is solved. Thank you, it's because of the Eigen version.
